version: "3"

services:
  postgres-wineme:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - wineme-db:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wineme

volumes:
  wineme-db: